# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if enabled_plugins.get('MOONCAKE') and is_variable('mooncake_backend_interface')
    subdir('mooncake')
endif

if enabled_plugins.get('UCCL')
    subdir('uccl')
endif

if enabled_plugins.get('AZURE_BLOB')
    subdir('azure_blob')
endif

if not enabled_plugins.get('OBJ')
    message('OBJ plugin not enabled, skipping plugins_gtest build')
    subdir_done()
endif

aws_s3 = dependency('aws-cpp-sdk-s3', static: false, required: false)
aws_s3_crt = dependency('aws-cpp-sdk-s3-crt', static: false, required: false)
if not aws_s3.found()
    message('aws-cpp-sdk-s3 not found, skipping plugins_gtest build')
    subdir_done()
endif
if not aws_s3_crt.found()
    message('aws-cpp-sdk-s3-crt not found, skipping plugins_gtest build')
    subdir_done()
endif

plugins_gtest_cpp_flags = []
plugins_gtest_cuda_deps = []
if cuda_dep.found()
    plugins_gtest_cpp_flags += '-DHAVE_CUDA'
    plugins_gtest_cuda_deps = [cuda_dep]
endif

plugins_gtest_sources = ['../main.cpp', '../common.cpp', 'obj_plugin.cpp']
if cuobj_dep.found()
    plugins_gtest_sources += 'obj_cuobj_plugin.cpp'
endif

plugins_test_exe = executable('plugins_gtest',
    sources : plugins_gtest_sources,
    include_directories: [nixl_inc_dirs, utils_inc_dirs, plugins_inc_dirs, '.'],
    cpp_args : plugins_gtest_cpp_flags,
    dependencies : [nixl_dep, gtest_dep, absl_strings_dep, absl_time_dep, plugin_deps,
                    obj_backend_interface] + plugins_gtest_cuda_deps,
    link_with: [nixl_build_lib],
    install : true
)

test('plugins_gtest', plugins_test_exe)
